config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :incomes

  root :to => 'application#home'

end

app/models/expense.rb
# == Schema Information
#
# Table name: transactions
#
#  id              :integer          not null, primary key
#  date            :date
#  source          :string
#  description     :text
#  amount_cents    :integer          default(0), not null
#  amount_currency :string           default("USD"), not null
#  attachment      :string
#  type            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Expense < Transaction
end

app/models/income.rb
# == Schema Information
#
# Table name: transactions
#
#  id              :integer          not null, primary key
#  date            :date
#  source          :string
#  description     :text
#  amount_cents    :integer          default(0), not null
#  amount_currency :string           default("USD"), not null
#  attachment      :string
#  type            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Income < Transaction
end

app/models/model.rb
# == Schema Information
#
# Table name: models
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  User                   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/paycheck.rb
# == Schema Information
#
# Table name: transactions
#
#  id              :integer          not null, primary key
#  date            :date
#  source          :string
#  description     :text
#  amount_cents    :integer          default(0), not null
#  amount_currency :string           default("USD"), not null
#  attachment      :string
#  type            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Paycheck < Transaction
end

app/models/tax_payment.rb
# == Schema Information
#
# Table name: transactions
#
#  id              :integer          not null, primary key
#  date            :date
#  source          :string
#  description     :text
#  amount_cents    :integer          default(0), not null
#  amount_currency :string           default("USD"), not null
#  attachment      :string
#  type            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class TaxPayment < Transaction
end

app/models/transaction.rb
# == Schema Information
#
# Table name: transactions
#
#  id              :integer          not null, primary key
#  date            :date
#  source          :string
#  description     :text
#  amount_cents    :integer          default(0), not null
#  amount_currency :string           default("USD"), not null
#  attachment      :string
#  type            :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Transaction < ActiveRecord::Base

  # ---------------------------------------- Plugins

  mount_uploader :attachment, AttachmentUploader

  monetize :amount_cents, :allow_nil => true

  # ---------------------------------------- Validations

  validates :date, :source, :amount_cents, :presence => true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base

  # ---------------------------------------- Plugins

  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
         :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery :with => :exception

  before_filter :authenticate_user!

  def home
  end

end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController

  def index
    @transactions = Income.all
  end

  def new
    @transaction = Income.new
  end

  def create
    @transaction = Income.new(income_params)
    if @transaction.save
      redirect_to incomes_path, :notice => 'Income saved successfully!'
    else
      render 'new'
    end
  end

  private

    def income_params
      params.require(:income).permit(:date, :source, :amount_cents)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def method_missing(method, *arguments, &block)
    super unless method.to_s.ends_with?('_controller?')
    controller_name == method.to_s.split('_').first
  end

end

app/views/application/_nav.html.erb
<nav class="navbar navbar-dark bg-primary navbar-fixed-top">
  <a class="navbar-brand" href="/">OpenCrate</a>
  <ul class="nav navbar-nav">
    <li class="nav-item <%= 'active' if incomes_controller? %>">
      <%= link_to 'Income', incomes_path, :class => 'nav-link' %>
    </li>
    <!-- <li class="nav-item">
      <a class="nav-link" href="#">Features</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">Pricing</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="#">About</a>
    </li> -->
  </ul>
  <ul class="nav navbar-nav pull-xs-right">
    <li class="nav-item">
      <%= link_to 'Sign Out', destroy_user_session_path, :method => :delete,
                  :class => 'nav-link' %>
    </li>
  </ul>
</nav>

app/views/application/_status.html.erb
<% if notice %>
  <p class="alert alert-info">
    <a href="#" data-dismiss="alert" class="close" aria-label="Close">&times;</a>
    <%= notice %>
  </p>
<% end %>
<% if alert %>
  <p class="alert alert-danger">
    <a href="#" data-dismiss="alert" class="close" aria-label="Close">&times;</a>
    <%= alert %>
  </p>
<% end %>

app/views/application/home.html.erb
<h1>Hello There</h1>

app/views/incomes/_form.html.erb
<%= simple_form_for @transaction do |f| %>
  <%= f.error_notification %>

  <%= f.input :date, :as => :string,
              :input_html => { :class => 'datepicker' } %>
  <%= f.input :source %>
  <div class="input">
    <label>Amount</label>
    <div class="input-group">
      <div class="input-group-addon">$</div>
      <%= f.input :amount, :as => :decimal, :wrapper => false,
                  :label => false %>
    </div>
  </div>

  <br>
  <%= f.button :submit %>
<% end %>

app/views/incomes/_income.html.erb
<tr>
  <td><%= income.date %></td>
  <td><%= income.source %></td>
  <td><%= income.amount.format %></td>
</tr>

app/views/incomes/index.html.erb
<div class="page-title">
  <h1>
    Income
    <a href="<%= new_income_path %>" class="btn btn-sm">
      <%= fa_icon 'plus', :text => 'New Income' %>
    </a>
  </h1>
</div>

<div class="content">
  <% if @transactions.present? %>
    <table class="table">
      <thead>
        <th>Date</th>
        <th>Source</th>
        <th>Amount</tr>
      </thead>
      <tbody>
        <%= render @transactions %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/incomes/new.html.erb
<div class="page-title">
  <h1>New Income</h1>
</div>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OpenCrate</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'nav' if user_signed_in? %>

    <div class="main container">
      <%= render 'status' %>
      <%= yield %>
    </div>

  </body>
</html>